# Linear queue for the main branch.
shared:
    commit_message_template: &commit-message-template |-
      {{ title }} (#{{ number }})

      {{ body | trim }}
    queue_checks: &queue-checks
      - base=main
      - or:
          - check-pending=integration-test-result
          - check-success=integration-test-result
          - label=bypass:integration
    merge_checks: &merge-checks
      - base=main
      # Require integration tests before merging only
      - or:
          - label=bypass:integration
          - check-success=integration-test-result
    priority_rules: &priority-rule-checks
      - name: high priority
        conditions:
          - label=priority:high
        priority: high

queue_rules:
  - name: rebase_main
    commit_message_template: *commit-message-template
    queue_conditions: *queue-checks
    merge_conditions: *merge-checks
    priority_rules: *priority-rule-checks
    merge_method: merge
    update_method: rebase

  - name: merge_main
    commit_message_template: *commit-message-template
    queue_conditions: *queue-checks
    merge_conditions: *merge-checks
    priority_rules: *priority-rule-checks
    disallow_checks_interruption_from_queues:
      - rebase_main
    merge_method: merge

  - name: squash_main
    commit_message_template: *commit-message-template
    queue_conditions: *queue-checks
    merge_conditions: *merge-checks
    priority_rules: *priority-rule-checks
    disallow_checks_interruption_from_queues:
      - rebase_main
      - merge_main
    merge_method: squash


pull_request_rules:
  - name: merge to master
    conditions:
      - base=main
      - label=automerge:no-update
      - or:
          - '#commits-behind=0'
          - label=bypass:linear-history
    actions:
      queue:
        name: merge_main
  - name: rebase updates then merge to master
    conditions:
      - base=main
      - label=automerge:rebase
    actions:
      queue:
        name: rebase_main
  - name: squash to master
    conditions:
      - base=main
      - label=automerge:squash
    actions:
      queue:
        name: squash_main
